INSERT INTO T_TXN_ADRESSE(ID_ADRESSE, NUM_RUE, LIBELLE_RUE, CODE_POSTAL, COMMUNE, PAYS) VALUES (1, '2', 'rue alexandre tass', '94000', 'chaneroux', 'FRANCE');
INSERT INTO T_TXN_ADRESSE(ID_ADRESSE, NUM_RUE, LIBELLE_RUE, CODE_POSTAL, COMMUNE, PAYS) VALUES (2, '19', 'boulevard de gaulle', '20000', 'tours', 'FRANCE');


INSERT INTO T_TXN_FOURNISSEUR(ID_FOURNISSEUR, NOM, TEL, ID_ADRESSE) VALUES (1, 'danone', '060000000', 2);
INSERT INTO T_TXN_FOURNISSEUR(ID_FOURNISSEUR, NOM, TEL, ID_ADRESSE) VALUES (2, 'total', '0610000', 1);


INSERT INTO T_TXN_FAMILLE_ARTICLE(ID_FAMILLE_ARTICLE, NOM, DESCRIPTION) VALUES (1, 'yaourt', 'produit laitier');


INSERT INTO T_TXN_ARTICLE(ID_ARTICLE, NOM, REFERENCE, COULEUR, DESCRIPTION, ID_FAM, ID_FOURNISSEUR) VALUES (1, 'fruite rouge', 'fruitrouge', 'rouge', '', 1, 2);
INSERT INTO T_TXN_ARTICLE(ID_ARTICLE, NOM, REFERENCE, COULEUR, DESCRIPTION, ID_FAM, ID_FOURNISSEUR) VALUES (2, 'fruite abricot', 'fruitrouge', 'jaune', '', 1, 1);
INSERT INTO T_TXN_ARTICLE(ID_ARTICLE, NOM, REFERENCE, COULEUR, DESCRIPTION, ID_FAM, ID_FOURNISSEUR) VALUES (3, 'arome ananas', 'ananas', 'blanc', '', 1, 1);


INSERT INTO T_TXN_CLIENT(ID_CLIENT, NOM, PRENOM, TEL, ID_ADRESSE) VALUES (1, 'VAILLANT', 'Michel', '033141100236', 2);

INSERT INTO T_REF_PRIVILEGES(ID_CLIENT, DROIT) VALUES (1, 'ACHETER');
INSERT INTO T_REF_PRIVILEGES(ID_CLIENT, DROIT) VALUES (1, 'VENDRE');
